### ISSUE TITLE
Supported MacOS

### ISSUE THREAD

**Issue by n-lavrenko** [AminHP/gym-mtsim#1]
I've check that there is no Metatrader 5 on pip, because it's support Windows OS only. 
As I understand, it's impossible to use your module outside of Windows, cause it's contains required for Windows only module. 
Maybe you could provide limited using of your module for MacOS / Linux without MetaTrader? 
Thank you for your great job, @AminHP!

**Comment by AminHP** [comment]
They recently released their software for Linux and Mac. I guess they will release the related pip modules soon. However, it is possible to use their software and python modules in Wine. Did you try that?
In case Wine didn't work for you, use [this](https://github.com/AminHP/gym-mtsim/tree/linux-mac) temporary version and install it via the command below:

`pip install https://github.com/AminHP/gym-mtsim/archive/refs/heads/linux-mac.zip`

Note that it is not possible to download new data by this temporary version.

**Comment by n-lavrenko** [comment]
Thank you. I will use 
`pip install https://github.com/AminHP/gym-mtsim/archive/refs/heads/linux-mac.zip`
as temporary solution.
