### ISSUE TITLE
questions on _process_data(), _get_observation() and multi symbols

### ISSUE THREAD

**Issue by yglpyn8888** [AminHP/gym-mtsim#11]
1 The **_process_data()** method takes the return value of _get_prices() as a feature, but the return value of _get_prices() is two columns of bar data which are close and open, and this  are not  features. Why?
2 _get_observation() returns a dict, but not a np.ndarray,  for a typicle gym env， Shouldn't the **observation** returned by the step method be a np.ndarray?
3 I see many data structures in this framework use Dict, which should be to support multiple symbols? I only load data of a single symbol, so should I change the underlying data structure,? or just put a single key (the single symbol i focus on) in the dict.

**Comment by yglpyn8888** [comment]
for question1 , i thought i understand that you just collect close and open as two features as an example, and i can override this method to load other feature columns what i want

**Comment by AminHP** [comment]
2. It should return Dict when the `observation_space` is an instance of `spaces.Dict`.
3. There is no need to change the structure. Just put a single key for the symbol you want. And make sure `simulator.unit` is in `symbol_info.currencies` for that symbol.
