### ISSUE TITLE
Training with CSV

### ISSUE THREAD

**Issue by TheSnowGuru** [AminHP/gym-mtsim#17]
Hello, thanks for this great repo, I wonder, why did you use pkl files and not csv's? 
and how can I replace the csv with my own data set to be in the form of csv or even metatrader files?

thanks

**Comment by AminHP** [comment]
Hi @TheSnowGuru,
Because a tuple of `simulator.symbols_info` and `simulator.symbols_data` is stored in the pkl files. This [link](https://github.com/AminHP/gym-mtsim/issues/8) might be useful.
