### ISSUE TITLE
Question about volume

### ISSUE THREAD

**Issue by sadimoodi** [AminHP/gym-mtsim#19]
Hello @AminHP ,

Do you know why is the volume value always small? i noticed its usually in small numbers such as in the rough range [-5,+5] 
I changed the volume to "Amount" but i didnt touch the action space (which should be [-inf,+inf]), i am wondering if the action space is close to inf, why am i getting very small numbers when the action is generated by gym?
I know i can mutiply or square the value, but was just wondering if i am missing something ? albeit i didnt change anything in the code.

**Comment by AminHP** [comment]
Hi @sadimoodi,
I think the agent learns that it can't pick a high volume because of balance limits.
