### ISSUE TITLE
Help!  Need balance history at each reward calculation

### ISSUE THREAD

**Issue by snafu4** [AminHP/gym-mtsim#2]
Unsuccessfully trying to get a list of all balance values within each timestep inside of the reward method.  So, at each call to _calculate_rewards(), I am trying to extract a list of all historical balances (for that timestep) - i.e. each call should add 1 historical balance.

I've tried calculating it within MtSimulator but this gets too complicated.

Poking around self.history but unable to successfully unwrap it for this.

Thanks

**Comment by AminHP** [comment]
Does this code do the job?
```python
[h['balance'] for h in self.history]
```

**Comment by snafu4** [comment]
Yes, I believe it does.  Thanks!
