### ISSUE TITLE
A Complete Example using stable-baselines

### ISSUE THREAD

**Issue by Error4046716** [AminHP/gym-mtsim#26]
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-6-4ca9ec63cf36>](https://localhost:8080/#) in <module>()
     11 # env = gym.make('crypto-hedge-v0')
     12 
---> 13 model = A2C('MultiInputPolicy', env, verbose=0)
     14 model.learn(total_timesteps=1000)
     15 

2 frames
[/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/base_class.py](https://localhost:8080/#) in __init__(self, policy, env, learning_rate, policy_kwargs, tensorboard_log, verbose, device, support_multi_env, create_eval_env, monitor_wrapper, seed, use_sde, sde_sample_freq, supported_action_spaces)
    189                 assert np.all(
    190                     np.isfinite(np.array([self.action_space.low, self.action_space.high]))
--> 191                 ), "Continuous action space must have a finite lower and upper bound"
    192 
    193     @staticmethod

AssertionError: Continuous action space must have a finite lower and upper bound
```

Where can set the lower and upper bound? Thank you

**Comment by AminHP** [comment]
Hi @Error4046716,

I added some commits to make the repo compatible with the newer versions of `gym`. However, `stable_baselines` is not compatible yet. You can try using `stable-baselines3==1.5.0` with `gym==0.21.0` for now. Also, you can change the lower and upper bound [here](https://github.com/AminHP/gym-mtsim/blob/40c08e98d8c2574560f0e5e8da35415b9e95b4db/gym_mtsim/envs/mt_env.py#L71).

**Comment by TomCS91** [comment]
This bug seems to still be active with the below versions.

Running torch 1.12.0 instead of 1.12.1 I thought fixed it as that worked on one machine but it didn't on another.

pip show stable-baselines3
Name: stable-baselines3
Version: 1.5.0

pip show gym
Name: gym
Version: 0.21.0

pip show torch
Name: torch
Version: 1.12.0

**Comment by salah2025** [comment]
How can I add technical indicators ?

**Comment by Emmanuel1524** [comment]
Just add some comment here: the Mtsim isnt working so well with StableBaseline3...

Even when I correct the Box adjustment bug, the algorithin doesn't  fit so well with the RL algos

**Comment by AminHP** [comment]
Please install the latest version (v1.3.0).
