### ISSUE TITLE
Run on MT5

### ISSUE THREAD

**Issue by nexon33** [AminHP/gym-mtsim#28]
Is it possible to run a created model on an actual MetaTrader5 Instance?

**Comment by AminHP** [comment]
Hi @nexon33, of course. You just need to download the MT5 data using its APIs in real-time. Then, feed that data to the model. Afterward, you can apply the decision made by the model using two MT5 APIs (create order and close order) in your actual account. Check out this [link](https://www.mql5.com/en/docs/integration/python_metatrader5) for more information about the MT5 APIs.
