### ISSUE TITLE
Possible to train the bot on 1H or 4H instead of D1? 

### ISSUE THREAD

**Issue by nexon33** [AminHP/gym-mtsim#29]
.

**Comment by nexon33** [comment]
I also seem to run into trouble when downloading data and my client will stop doing trades and have 0 balance and 0 reward.

**Comment by AminHP** [comment]
You are welcome to contact me via email. It is available on my Github page.

I did not understand this issue. Can you send an example code to reproduce the error?

**Comment by nexon33** [comment]
I have sent to email.

If I train the model after a while it will just choose to not do any trades anymore

**Comment by AminHP** [comment]
I didn't receive your email.

**Comment by nexon33** [comment]
Weird, well I'll just post it here.

![image](https://user-images.githubusercontent.com/47557266/185467417-46a46c1e-d0eb-4287-9c34-c624a1afd8ff.png)

I get this after the model has been training some time.  I'm using A2C model. Already tried increasing reward on opening orders so the bot tries open more orders. 

I'm also looking for a way to add Indicators to the environment so the bot can use the values

**Comment by nexon33** [comment]
I figured I'd probably need to use a custom model, but I'm failing to put the observation and action space into the

```
Model.add(Dense(228, activation=relu, input_shape=???)
```
But it doesnt accept dict

**Comment by nexon33** [comment]
Fixed it

**Comment by nexon33** [comment]
turns out I didn't completely. Please check your email as my email might have gone into spam.
