### ISSUE TITLE
How can I add technical indicators ?

### ISSUE THREAD

**Issue by salah2025** [AminHP/gym-mtsim#31]
please help me to add technical indicator like any trading

**Comment by AminHP** [comment]
Hi @salah2025,

You can override [this](https://github.com/AminHP/gym-mtsim/blob/96ae011a6d7562420cb9486bab62402b3d969b9b/gym_mtsim/envs/mt_env.py#L209) method and change `signal_fetures`. The indicators can be added to `signal_featuers`.
