### ISSUE TITLE
example: environment with custom parameters

### ISSUE THREAD

**Issue by kruzel** [AminHP/gym-mtsim#32]
this example does not open any trades
```
balance: 10000.0, equity: 10000.0, margin: 0.0
free_margin: 10000.0, margin_level: inf
```

just different from expected results you wrote

**Comment by crayola-web** [comment]
Increase the hold_threshold parameter, by default it is 0.5 maximum 1 this parameter holds to open the orders.

**Comment by AminHP** [comment]
Can you send a complete example?

**Comment by kruzel** [comment]
sorry, its the example in the readme
![image](https://user-images.githubusercontent.com/975963/211161886-2dd4ce5d-c380-4f8a-bcb9-12abf23b125f.png)

**Comment by kruzel** [comment]
it was this one, but now working for me, closing
![image](https://user-images.githubusercontent.com/975963/211162646-a9649d5a-5264-4180-8d33-8301dc1bb9ac.png)
