### ISSUE TITLE
Should use open price instead of close price

### ISSUE THREAD

**Issue by luxiaolei** [AminHP/gym-mtsim#35]
Hi HP,

Thanks for ur great project, just a thought on line 85 of `mt_simulator.py`

        for order in self.orders:
            order.exit_time = self.current_time
            order.exit_price = self.price_at(order.symbol, order.exit_time)['Close'] # Should be Open price
            self._update_order_profit(order)
            self.equity += order.profit

I think you meant open price? because the candlestick is timed at the open time of the bar.

**Comment by AminHP** [comment]
Hi @luxiaolei ,

The actual value at the time of trading is somewhere between High and Low prices. However, due to the simulation limits, an approximate value (such as Close and Open price or even `(Close+Open)/2`) can work. You can choose what most suits you.

**Comment by luxiaolei** [comment]
I see, thanks:)
