### ISSUE TITLE
AssertionError: Continuous action space must have a finite lower and upper bound

### ISSUE THREAD

**Issue by D-forti** [AminHP/gym-mtsim#36]
Model seems working fine, when I try model.learn, I get the error.

If I adjust upper and lower bound in the action space (low=-1e10, high=1e10) the model does not place any order.

**Comment by AminHP** [comment]
Does this fix (#30) work for you?

**Comment by D-forti** [comment]
yes! Now it works! thanks!

**Comment by AminHP** [comment]
The PR has been merged into the main branch. Please install the latest version (v1.3.0).

**Comment by D-forti** [comment]
Yes, it is working well now, however, I am struggling a lot to find a way to train an agent using RL for an intraday trading bot...
