### ISSUE TITLE
Incompatibility with Linux systems

### ISSUE THREAD

**Issue by bangxiangyong** [AminHP/gym-mtsim#38]
One of the core dependency, `MetaTrader5` is only available to Windows but not Linux. This causes the `gym-mtsim` to be unable to run on Linux machines.

**Comment by AminHP** [comment]
Yes that's right. At the time I started this project, they promised to make MetaTrader5 compatible with Linux and macOS. But they haven't published anything yet. I created [a branch](https://github.com/AminHP/gym-mtsim/tree/linux-mac) in this repo to support Linux and macOS. However, it's not updated. I will update this branch soon and release a new version.

**Comment by AminHP** [comment]
Please install the latest version (v1.3.0). The repo can now be installed on Linux and macOS. Note that the `download_data` method only works on Windows.
