### ISSUE TITLE
Feature Request: update from gym to gymnasium

### ISSUE THREAD

**Issue by elliottower** [AminHP/gym-mtsim#39]
Hi, this repository is currently listed in the gymnasium [third party environments](https://gymnasium.farama.org/environments/third_party_environments/) but we are cleaning the list up to only include maintained gymnasium-compatible repositories.  

Would it be possible for it to be upgraded from gym to gymnasium? [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of openai gym and is compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib) and [tianshou](https://github.com/thu-ml/tianshou) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon).  

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

**Comment by Alex2782** [comment]
https://github.com/AminHP/gym-mtsim/pull/40

The render() function is not yet compatible with SB3 + Gymnasium. 
'gym-mtsim' is not a classic render environment, I don't know if it will be easy.

**Comment by AminHP** [comment]
I just merged the PR and made the library compatible with the latest gymnasium.
I will release a new version after adding some improvements to the repo.
Thanks again @elliottower and @Alex2782 .

**Comment by elliottower** [comment]
Nice to hear, if you have time to it would be great if you could create a pr updating https://github.com/Farama-Foundation/Gymnasium/blob/main/docs/environments/third_party_environments.md with updated info and such (easier if the creators write the language themselves so I or someone someone else don’t butcher it)
