### ISSUE TITLE
Recommended workflow for debugging changes to gym-mtsim

### ISSUE THREAD

**Issue by dancydancy** [AminHP/gym-mtsim#7]
Hi Amin,

What workflow do you recommend to debug changes if overriding methods and testing. This is for making sure everything is correct before training, but could also apply for training cycle itself.

Many thanks.

**Comment by AminHP** [comment]
Hi @dancydancy

Can you be more specific and give an example?
Generally, I debug it by placing and closing some orders at certain time points. Then I calculate their profit manually and check if the code works correctly.
