### ISSUE TITLE
Pickle files

### ISSUE THREAD

**Issue by sadimoodi** [AminHP/gym-mtsim#9]
Hello @AminHP ,
What data do you store inside the pickle files in the data folder?

**Comment by AminHP** [comment]
The data is stored by the [`save_symbols`](https://github.com/AminHP/gym-mtsim/blob/main/gym_mtsim/simulator/mt_simulator.py#L64) method. It's a tuple of `simulator.symbols_info` and `simulator.symbols_data`.
